"use client";

import { useEffect, useMemo, useState } from "react";

type Module = {id:string;title:string;duration:string;summary:string;keyPoints:string[];activity:string;reflection:string};
const modules:Module[]=[
{id:"foundations",title:"1. Understanding the Zones",duration:"25 min",summary:"Build a shared, non-judgemental understanding of regulation states and why every zone is valid.",keyPoints:["Zones describe states, not people.","Green is not the only acceptable zone.","Visible behaviour is incomplete information.","Pupil voice and context should shape interpretation."],activity:"Take three common classroom behaviours and write two possible regulation explanations for each.",reflection:"Where could staff language accidentally turn a temporary zone into a label?"},
{id:"language",title:"2. Language that supports regulation",duration:"30 min",summary:"Practise neutral noticing, acknowledgement, bounded choice and one clear next step.",keyPoints:["Reduce verbal load when arousal rises.","Acknowledge without removing boundaries.","Use concrete choices rather than open-ended demands.","Problem-solving works better after regulation."],activity:"Rewrite a high-demand correction into: neutral notice → boundary → two choices → next step.",reflection:"Which phrases used in your setting are most likely to escalate rather than regulate?"},
{id:"coreg",title:"3. Co-regulation and adult response",duration:"30 min",summary:"Understand how adult pace, tone, proximity and predictability influence pupil regulation.",keyPoints:["Adults can lend calm through pace and predictability.","Co-regulation is not permissiveness.","Safety and dignity can be maintained together.","Return conversations should happen when pupils can process them."],activity:"Map an escalation sequence and identify the earliest point an adult response could change the trajectory.",reflection:"What adult behaviour is easiest for you to change consistently?"},
{id:"classroom",title:"4. Classroom and subject implementation",duration:"35 min",summary:"Move Zones from posters into routines, transitions, practical work and subject-specific teaching.",keyPoints:["Predictable transitions reduce unnecessary demand.","Visual sequences can support access without reducing challenge.","Practical and high-energy lessons need deliberate regulation routines.","The best strategy preserves the learning goal."],activity:"Choose one lesson this week and design a 90-second regulation-friendly transition into its hardest phase.",reflection:"What part of your subject creates the greatest regulation demand?"},
{id:"intervention",title:"5. Targeted interventions",duration:"35 min",summary:"Build small, testable support plans linked to a clear barrier and review cycle.",keyPoints:["Start with the barrier, not a preferred strategy.","Keep strategies observable and teachable.","Define what improvement would look like.","Review fidelity and pupil usefulness as well as outcomes."],activity:"Write one intervention as: barrier → strategy → adult action → pupil action → review evidence.",reflection:"How will you know whether the strategy was genuinely used as intended?"},
{id:"school",title:"6. Whole-school implementation",duration:"40 min",summary:"Create consistency without making the framework rigid or performative.",keyPoints:["Shared language matters more than identical scripts.","Implementation should be modelled, rehearsed and revisited.","Leaders should look for changed practice, not only course completion.","Pupil feedback should shape refinements."],activity:"Audit one school routine and identify where Zones language, environment or adult response should become more consistent.",reflection:"What would convincing evidence of whole-school impact look like in 8–12 weeks?"},
];

export default function ZonesCpdPage(){
 const [selected,setSelected]=useState(modules[0].id);const [complete,setComplete]=useState<string[]>([]);const [slide,setSlide]=useState(0);const [reflection,setReflection]=useState("");
 useEffect(()=>{try{setComplete(JSON.parse(localStorage.getItem("staff-development-zones-cpd")||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("staff-development-zones-cpd",JSON.stringify(complete))},[complete]);
 const mod=modules.find(x=>x.id===selected)!;const slides=useMemo(()=>[{title:mod.title,text:mod.summary},{title:"Key ideas",points:mod.keyPoints},{title:"Application task",text:mod.activity},{title:"Reflection",text:mod.reflection}],[mod]);
 function choose(id:string){setSelected(id);setSlide(0);setReflection("")}
 function mark(){setComplete(v=>v.includes(mod.id)?v:[...v,mod.id])}
 return <main className="zsPage"><section className="zsHero compact"><div><span className="zsEyebrow">ZONES CPD ACADEMY</span><h1>Dedicated professional learning for regulation practice.</h1><p>This restores the original Zones-specific CPD area alongside the broader CPD library. Use it for individual learning, department discussion or facilitated whole-staff training.</p></div><div className="zsProgressRing"><strong>{complete.length}/{modules.length}</strong><span>modules complete</span></div></section>
 <section className="zcToolRow"><a href="/zones-cpd/escape-room"><span>⌁</span><b>CPD Escape Room</b><small>Immersive case-based staff challenge</small></a><a href="/zone-quest"><span>◆</span><b>Zone Quest</b><small>Fast scenario game and team activity</small></a><a href="/regulation-room"><span>◇</span><b>Regulation Room</b><small>Experience the pupil-facing tools</small></a><a href="/live"><span>◫</span><b>Live CPD</b><small>Run interactive staff sessions</small></a></section>
 <section className="zcGrid"><aside className="zcModuleList"><span className="zsEyebrow">COURSE SEQUENCE</span>{modules.map(item=><button className={selected===item.id?"active":""} onClick={()=>choose(item.id)} key={item.id}><span>{complete.includes(item.id)?"✓":"○"}</span><div><strong>{item.title}</strong><small>{item.duration}</small></div></button>)}</aside>
 <article className="zcDeck"><header><div><span className="zsEyebrow">FACILITATOR DECK</span><h2>{mod.title}</h2></div><span>{slide+1}/{slides.length}</span></header><div className="zcSlide"><span className="zcSlideNumber">0{slide+1}</span><h3>{slides[slide].title}</h3>{slides[slide].text&&<p>{slides[slide].text}</p>}{slides[slide].points&&<ul>{slides[slide].points?.map(point=><li key={point}>{point}</li>)}</ul>}{slide===3&&<textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Write your reflection or team notes here…"/>}</div><footer><button disabled={slide===0} onClick={()=>setSlide(v=>Math.max(0,v-1))}>← Previous</button><div>{slides.map((_,i)=><i className={i===slide?"on":""} key={i}/>)}</div>{slide<slides.length-1?<button className="zsPrimary" onClick={()=>setSlide(v=>v+1)}>Next →</button>:<button className="zsPrimary" onClick={mark}>{complete.includes(mod.id)?"Completed ✓":"Mark module complete"}</button>}</footer></article>
 <aside className="zcPractice"><span className="zsEyebrow">APPLY IT</span><h3>Practical task</h3><p>{mod.activity}</p><h3>Reflection</h3><p>{mod.reflection}</p><a href="/zones-cpd/escape-room">Use an escape-room case →</a></aside></section>
 <section className="zsStrip"><div><b>Facilitator use</b><span>Project the deck, discuss the task, then capture a shared next action.</span></div><div><b>Individual use</b><span>Work through the same content and keep your own implementation reflection.</span></div><div><b>Next step</b><span>Use the Escape Room or Zone Quest to rehearse judgement rather than memorise labels.</span></div></section></main>
}
