"use client";

import { useEffect, useMemo, useState } from "react";
import { environmentCriteria, impactMetrics, implementationAudit, legacyResources, legacySubjects, lessonFramework, observationItems, rolloutMilestones, transitions, tutorActivities } from "@/lib/zonesMigrationData";

type Tab="insights"|"subjects"|"planner"|"resources"|"implementation"|"impact"|"operations"|"settings";
type LegacyState={audit:boolean[];metrics:Record<string,number>;rollout:boolean[];schoolName:string;notes:string;observations:boolean[];environment:boolean[]};
const key="staff-development-zones-school-v1";
const defaults:LegacyState={audit:implementationAudit.map(()=>false),metrics:Object.fromEntries(impactMetrics.map((x,i)=>[x,[65,55,50,35,45,30][i]||50])),rollout:rolloutMilestones.map(()=>false),schoolName:"Your School",notes:"",observations:observationItems.map(()=>false),environment:environmentCriteria.map(()=>false)};

export default function ZonesSchoolPage(){
 const [tab,setTab]=useState<Tab>("insights");const [state,setState]=useState<LegacyState>(defaults);const [ready,setReady]=useState(false);const [subjectId,setSubjectId]=useState("science");const [phase,setPhase]=useState("KS3");const [goal,setGoal]=useState("");const [transition,setTransition]=useState(Object.keys(transitions)[0]);
 useEffect(()=>{try{const s=localStorage.getItem(key);if(s)setState({...defaults,...JSON.parse(s)})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(state))},[ready,state]);
 const platform=useMemo(()=>{if(typeof window==="undefined")return {checkIns:[],interventions:[]};try{return JSON.parse(localStorage.getItem("staff-development-platform-v1")||"{}") as {checkIns?:{zone:string;createdAt:string}[];interventions?:{status:string}[]}}catch{return {checkIns:[],interventions:[]}}},[ready]);
 const checkIns=platform.checkIns||[],interventions=platform.interventions||[];const counts=["blue","green","yellow","red"].map(z=>({z,n:checkIns.filter(x=>x.zone===z).length}));
 const subject=legacySubjects.find(x=>x.id===subjectId)||legacySubjects[0];const auditPct=Math.round(100*state.audit.filter(Boolean).length/Math.max(1,state.audit.length));const impact=Math.round(Object.values(state.metrics).reduce((a,b)=>a+b,0)/Math.max(1,Object.values(state.metrics).length));
 if(!ready)return <main className="zmPage"><p>Opening whole-school toolkit…</p></main>;
 return <main className="zmPage"><section className="zmHero"><div><span>WHOLE-SCHOOL REGULATION PLATFORM</span><h1>Every original school implementation tool in one workspace.</h1><p>Insights, subject guidance, lesson planning, resources, implementation review, impact evidence and school operations have been migrated from the original Zones app into the unified Staff Development login.</p></div><div className="zmScore"><b>{impact}%</b><small>implementation pulse</small></div></section>
 <nav className="zmTabs">{([['insights','Local Insights'],['subjects','Subjects'],['planner','Lesson Planner'],['resources','Resources'],['implementation','Implementation'],['impact','Impact Hub'],['operations','School Operations'],['settings','About & Settings']] as [Tab,string][]).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==='insights'&&<section className="zmStack"><div className="zmGrid4"><Metric n={checkIns.length} label="Check-ins"/><Metric n={interventions.filter(x=>x.status!=="Complete").length} label="Active interventions"/><Metric n={auditPct+"%"} label="Implementation"/><Metric n={impact+"%"} label="Impact score"/></div><div className="zmGrid2"><Panel title="Regulation snapshots"><div className="zmZoneBars">{counts.map(x=><div key={x.z}><span className={x.z}/><strong>{x.z[0].toUpperCase()+x.z.slice(1)}</strong><i><b style={{width:`${checkIns.length?Math.max(4,100*x.n/checkIns.length):0}%`}}/></i><em>{x.n}</em></div>)}</div><p className="zmNote">These are snapshots, not labels. Use context, pupil voice, lesson patterns and strategy impact before drawing conclusions.</p></Panel><Panel title="Evidence prompts"><ul>{["When are regulation difficulties most likely to appear?","Which routines appear to reduce uncertainty?","Are pupils using support discreetly and with dignity?","Which strategies help return to learning rather than only reduce visible behaviour?"].map(x=><li key={x}>{x}</li>)}</ul></Panel></div></section>}
 {tab==='subjects'&&<section className="zmGrid2"><Panel title="Curriculum implementation"><label className="zmField">Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{legacySubjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><div className="zmPills">{subject.phases.map(x=><span key={x}>{x}</span>)}</div><h3>Likely pressure points</h3><ul>{subject.challenges.map(x=><li key={x}>{x}</li>)}</ul></Panel><Panel title={`${subject.name} strategies`}><h3>Classroom approaches</h3><ul>{subject.strategies.map(x=><li key={x}>{x}</li>)}</ul><h3>Useful routines</h3><div className="zmCardsMini">{subject.routines.map(x=><span key={x}>{x}</span>)}</div></Panel></section>}
 {tab==='planner'&&<section className="zmGrid2"><Panel title="Regulation-aware lesson planner"><label className="zmField">Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{legacySubjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="zmField">Phase<select value={phase} onChange={e=>setPhase(e.target.value)}>{["Primary","KS3","GCSE","Sixth Form"].map(x=><option key={x}>{x}</option>)}</select></label><label className="zmField">Lesson goal<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="What should pupils know or be able to do?"/></label><button className="zmPrimary" onClick={()=>window.print()}>Print / save lesson plan</button></Panel><Panel title={`${subject.name} · ${phase}`}><p><strong>Learning goal:</strong> {goal||"Add your lesson goal to personalise this plan."}</p><PlanBlock title="Before learning" items={[...lessonFramework.before,subject.routines[0]]}/><PlanBlock title="During learning" items={[...lessonFramework.during,...subject.strategies.slice(0,2)]}/><PlanBlock title="Transition / close" items={[...lessonFramework.after,subject.routines.at(-1)||""]}/></Panel></section>}
 {tab==='resources'&&<section className="zmResourceGrid">{legacyResources.map(r=><article className="zmResource" key={r.title}><span>{r.audience}</span><h2>{r.title}</h2><p>{r.desc}</p><button onClick={()=>printResource(r.title,r.desc)}>Open printable →</button></article>)}</section>}
 {tab==='implementation'&&<section className="zmGrid2"><Panel title={`Whole-school audit · ${auditPct}%`}><div className="zmChecks">{implementationAudit.map((x,i)=><label key={x}><input type="checkbox" checked={!!state.audit[i]} onChange={()=>setState(s=>({...s,audit:s.audit.map((v,j)=>j===i?!v:v)}))}/><span>{x}</span></label>)}</div></Panel><Panel title="90-day rollout"><div className="zmChecks">{rolloutMilestones.map((x,i)=><label key={x}><input type="checkbox" checked={!!state.rollout[i]} onChange={()=>setState(s=>({...s,rollout:s.rollout.map((v,j)=>j===i?!v:v)}))}/><span><strong>Day {[1,7,14,30,45,60,75,90][i]}</strong> · {x}</span></label>)}</div></Panel></section>}
 {tab==='impact'&&<section className="zmGrid2"><Panel title="Implementation scorecard">{impactMetrics.map(label=><label className="zmMetric" key={label}><span>{label}<b>{state.metrics[label]}%</b></span><input type="range" min="0" max="100" value={state.metrics[label]} onChange={e=>setState(s=>({...s,metrics:{...s.metrics,[label]:Number(e.target.value)}}))}/></label>)}</Panel><Panel title="Leadership evidence trail"><p>Use this alongside CPD completion, pupil/staff voice, intervention reviews and subject evidence.</p><label className="zmField">Review notes<textarea value={state.notes} onChange={e=>setState(s=>({...s,notes:e.target.value}))} placeholder="Strengths, barriers, evidence and agreed next actions…"/></label><div className="zmImpactSummary"><b>{impact}%</b><span>{impact>=75?'Strong implementation evidence':impact>=45?'Developing implementation':'Priority action required'}</span></div><a className="zmPrimary link" href="/impact">Open full CPD Impact tool</a></Panel></section>}
 {tab==='operations'&&<section className="zmStack"><div className="zmGrid2"><Panel title="Tutor & pastoral routines"><div className="zmCardsMini vertical">{tutorActivities.map(a=><article key={a.name}><strong>{a.name} · {a.minutes} min</strong><ol>{a.steps.map(x=><li key={x}>{x}</li>)}</ol></article>)}</div></Panel><Panel title="Transition planner"><label className="zmField">Transition<select value={transition} onChange={e=>setTransition(e.target.value)}>{Object.keys(transitions).map(x=><option key={x}>{x}</option>)}</select></label><ul>{transitions[transition as keyof typeof transitions].map(x=><li key={x}>{x}</li>)}</ul></Panel></div><div className="zmGrid2"><Panel title="Learning walk / observation"><div className="zmChecks">{observationItems.map((x,i)=><label key={x}><input type="checkbox" checked={state.observations[i]} onChange={()=>setState(s=>({...s,observations:s.observations.map((v,j)=>j===i?!v:v)}))}/><span>{x}</span></label>)}</div></Panel><Panel title="Environment audit"><div className="zmChecks">{environmentCriteria.map((x,i)=><label key={x}><input type="checkbox" checked={state.environment[i]} onChange={()=>setState(s=>({...s,environment:s.environment.map((v,j)=>j===i?!v:v)}))}/><span>{x}</span></label>)}</div></Panel></div></section>}
 {tab==='settings'&&<section className="zmGrid2"><Panel title="School settings"><label className="zmField">School / organisation name<input value={state.schoolName} onChange={e=>setState(s=>({...s,schoolName:e.target.value}))}/></label><p>All of these migrated Zones tools use the same Staff Development account. The original standalone Zones password gate has deliberately not been restored.</p></Panel><Panel title="Support boundaries"><ul><li>Every zone is valid; zones describe states, not pupils.</li><li>Regulation support is not a behaviour sanction or reward system.</li><li>Safeguarding, medical and emergency concerns follow normal school procedures.</li><li>Use pupil voice and context when reviewing patterns.</li></ul><a className="zmPrimary link" href="/zones">Back to Zones overview</a></Panel></section>}
 </main>
}
function Metric({n,label}:{n:string|number;label:string}){return <div className="zmMetricCard"><b>{n}</b><span>{label}</span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="zmPanel"><h2>{title}</h2>{children}</section>}
function PlanBlock({title,items}:{title:string;items:string[]}){return <div className="zmPlanBlock"><strong>{title}</strong><ul>{items.filter(Boolean).map(x=><li key={x}>{x}</li>)}</ul></div>}
function printResource(title:string,desc:string){const w=window.open("","_blank","width=850,height=900");if(!w)return;w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;padding:48px;color:#173840}h1{color:#126e5a}section{border:1px solid #ccdcd8;padding:24px;border-radius:12px;margin:18px 0}li{margin:10px 0}</style></head><body><h1>${title}</h1><p>${desc}</p><section><h2>Notice</h2><ul><li>What am I noticing in my energy, thoughts or body?</li><li>What is happening around me?</li></ul></section><section><h2>Choose support</h2><ul><li>What could make the next step easier?</li><li>Which strategy has helped before?</li><li>Do I need an adult, adjustment or short reset?</li></ul></section><section><h2>Review</h2><ul><li>Did the strategy help me access the next useful action?</li><li>What should I repeat or change next time?</li></ul></section></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
