"use client";

import { useMemo, useState } from "react";

type Room={id:string;title:string;subject:string;caseText:string;focus:string;barrier:string;bestResponse:string};
const rooms:Room[]=[
{id:"overloaded",title:"The Overloaded Classroom",subject:"Whole school",caseText:"A pupil who usually contributes stops writing, shortens their speech and leaves the group after the task changes.",focus:"Identify what changed in the environment, task and adult response before choosing support.",barrier:"uncertainty",bestResponse:"Show the first step, reduce simultaneous instructions and check privately."},
{id:"transition",title:"The Difficult Transition",subject:"Pastoral / whole school",caseText:"A class returns from lunch with high energy. Several pupils miss the starter and repeated verbal reminders increase.",focus:"Redesign the first two minutes so the transition is predictable and low-friction.",barrier:"transition",bestResponse:"Use a visible arrival routine with one first action and less repeated language."},
{id:"practical",title:"The Practical Lesson",subject:"Science / DT",caseText:"Equipment collection starts while a safety explanation is still happening, creating movement, noise and missed instructions.",focus:"Separate movement from safety communication while preserving practical challenge.",barrier:"simultaneous demand",bestResponse:"Finish safety communication before releasing equipment and pre-assign roles."},
{id:"assessment",title:"The Assessment Room",subject:"All subjects",caseText:"A pupil repeatedly checks instructions, freezes on multi-step items and becomes less responsive as time pressure increases.",focus:"Preserve assessment validity while reducing unnecessary access barriers.",barrier:"working memory",bestResponse:"Chunk access instructions without coaching the assessed content."},
{id:"playground",title:"The Playground Incident",subject:"Pastoral",caseText:"After a busy social incident, a pupil returns to class with short speech and difficulty starting.",focus:"Separate immediate access and safety support from later reflection.",barrier:"residual arousal",bestResponse:"Offer a low-language restart and revisit the incident after regulation."},
{id:"return",title:"Return to Learning",subject:"All subjects",caseText:"After a difficult moment, a pupil is ready to re-enter but does not know what has been missed or what to do first.",focus:"Create a dignified and predictable route back into learning.",barrier:"unclear re-entry",bestResponse:"Give one first task, one catch-up route and a discreet adult check-in."},
{id:"science",title:"Science Practical: Pressure Point",subject:"Science",caseText:"A pupil understands the physics but becomes stuck when instructions, apparatus setup and group roles arrive at once.",focus:"Reduce simultaneous demand without reducing scientific challenge.",barrier:"load",bestResponse:"Separate the instructions, apparatus setup and role allocation into visible phases."},
{id:"maths",title:"Maths: Multi-step Mystery",subject:"Maths",caseText:"A pupil can complete individual operations but stalls when a long problem must be held in working memory.",focus:"Maintain mathematical reasoning while reducing avoidable working-memory load.",barrier:"working memory",bestResponse:"Use a consistent chunking routine and visible intermediate steps."},
{id:"english",title:"English: Public Performance",subject:"English",caseText:"A pupil contributes in writing but freezes when unexpectedly asked to read aloud.",focus:"Preserve participation while reducing unnecessary public-performance demand.",barrier:"performance demand",bestResponse:"Offer predictable participation choices without removing the learning goal."},
];
const evidence=[
{kind:"Observation",text:"Speech shortened immediately after the task changed.",good:true},{kind:"Observation",text:"The pupil moved away from the group during equipment collection.",good:true},{kind:"Pupil voice",text:"“I knew what to do until everyone started moving.”",good:true},{kind:"Implementation",text:"The visual sequence was used in only 3 of 5 planned lessons.",good:true},{kind:"Outcome",text:"Task starts improved when the first step was visible.",good:true},{kind:"Inference",text:"The pupil was trying to avoid work.",good:false},{kind:"Environment",text:"Noise rose during the safety instruction.",good:true},{kind:"Language",text:"Four instructions were delivered in one spoken turn.",good:true},
];
const roles=[{id:"observer",name:"Observer",icon:"👁️",clue:"Watch what changes before the difficulty. Focus on observable signals."},{id:"evidence",name:"Evidence Analyst",icon:"📊",clue:"Check outcome, fidelity, pupil usefulness and context."},{id:"language",name:"Communication Lead",icon:"💬",clue:"Look for neutral notice, acknowledgement, clear goal and one next step."},{id:"environment",name:"Environment Lead",icon:"🏫",clue:"Inspect noise, movement, visual competition and uncertainty."}];

export default function EscapeRoomPage(){
 const [roomId,setRoomId]=useState("overloaded");const [stage,setStage]=useState(0);const [role,setRole]=useState("observer");const [chosenEvidence,setChosenEvidence]=useState<number[]>([]);const [barrier,setBarrier]=useState("");const [response,setResponse]=useState("");const [message,setMessage]=useState("");const [builderOpen,setBuilderOpen]=useState(false);const [customTitle,setCustomTitle]=useState("My CPD Escape Room");const [customCase,setCustomCase]=useState("");const [customClue,setCustomClue]=useState("");
 const room=rooms.find(x=>x.id===roomId)!;const progress=Math.round(stage/6*100);const roleInfo=roles.find(x=>x.id===role)!;
 const stageTitle=useMemo(()=>["Briefing","Evidence sweep","Find the barrier","Repair the response","Incoming evidence","Unlock the plan","Debrief"][stage],[stage]);
 function reset(id=roomId){setRoomId(id);setStage(0);setChosenEvidence([]);setBarrier("");setResponse("");setMessage("")}
 function next(){if(stage===1&&chosenEvidence.length<3){setMessage("Collect at least three evidence clues before moving on.");return}if(stage===2&&!barrier){setMessage("Choose the main access barrier first.");return}if(stage===3&&!response){setMessage("Choose an adult response first.");return}setMessage("");setStage(v=>Math.min(6,v+1))}
 return <main className="zsPage erPage"><section className="erHero"><div><span className="zsEyebrow">ZONES CPD ESCAPE ROOM</span><h1>{room.title}</h1><p>{room.caseText}</p><div className="erMeta"><span>{room.subject}</span><span>Stage {stage+1}/7</span><span>{roleInfo.icon} {roleInfo.name}</span></div></div><div className="erProgress"><div><i style={{width:`${progress}%`}}/></div><strong>{progress}%</strong><button onClick={()=>setBuilderOpen(true)}>Escape Room Builder</button></div></section>
 <section className="erLayout"><aside className="erLibrary"><span className="zsEyebrow">ROOM LIBRARY</span>{rooms.map(item=><button className={roomId===item.id?"active":""} onClick={()=>reset(item.id)} key={item.id}><strong>{item.title}</strong><small>{item.subject}</small></button>)}</aside>
 <article className="erStage"><header><span className="zsEyebrow">STAGE {stage+1}</span><h2>{stageTitle}</h2></header>
 {stage===0&&<div className="erBrief"><div className="erCaseFile"><span>CASE FILE</span><h3>{room.title}</h3><p>{room.caseText}</p><strong>Mission</strong><p>{room.focus}</p></div><h3>Choose a team role</h3><div className="erRoleGrid">{roles.map(item=><button className={role===item.id?"active":""} onClick={()=>setRole(item.id)} key={item.id}><span>{item.icon}</span><strong>{item.name}</strong><small>{item.clue}</small></button>)}</div></div>}
 {stage===1&&<div><p className="erInstruction">Inspect the case. Select evidence that should influence your decision. Avoid treating inference as fact.</p><div className="erEvidenceGrid">{evidence.map((item,i)=><button className={chosenEvidence.includes(i)?"selected":""} onClick={()=>setChosenEvidence(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])} key={i}><span>{item.kind}</span><p>{item.text}</p></button>)}</div><div className="erClue">Role clue: {roleInfo.clue}</div></div>}
 {stage===2&&<div><p className="erInstruction">What is the most useful description of the barrier in this case?</p><div className="erChoiceGrid">{[room.barrier,"poor attitude","lack of ability","deliberate defiance"].map(item=><button className={barrier===item?"active":""} onClick={()=>setBarrier(item)} key={item}>{item}</button>)}</div>{barrier&&<div className={barrier===room.barrier?"erFeedback success":"erFeedback"}>{barrier===room.barrier?"That description stays close to the evidence and gives staff something they can change.":"That choice risks turning an interpretation into a pupil label. Re-check the evidence."}</div>}</div>}
 {stage===3&&<div><p className="erInstruction">Choose the adult response most likely to preserve the learning goal while reducing unnecessary demand.</p><div className="erChoiceGrid wide">{[room.bestResponse,"Repeat the instruction more firmly until the pupil complies.","Remove the learning task completely.","Ask the pupil to explain their behaviour in front of the group."].map(item=><button className={response===item?"active":""} onClick={()=>setResponse(item)} key={item}>{item}</button>)}</div>{response&&<div className={response===room.bestResponse?"erFeedback success":"erFeedback"}>{response===room.bestResponse?"Strong choice: it changes access conditions without lowering the core learning goal.":"Consider whether this increases demand, removes challenge or adds public pressure."}</div>}</div>}
 {stage===4&&<div className="erIncoming"><span>INCOMING MESSAGE</span><h3>Pupil voice</h3><blockquote>“It is hardest when I do not know which thing matters first. Talking to me quietly is easier than everyone looking at me.”</blockquote><h3>Implementation evidence</h3><p>The same task went better when roles were allocated before equipment moved.</p><div className="erClue">Update your interpretation: does the new evidence support or challenge your current plan?</div></div>}
 {stage===5&&<div><p className="erInstruction">Unlock the plan by choosing the three ingredients a useful regulation support plan needs.</p><div className="erLockGrid">{["Clear barrier","Specific adult action","Review evidence","Permanent zone label","Lower expectations","Public behaviour chart"].map(item=><button key={item}>{item}</button>)}</div><div className="erPlanCard"><strong>Barrier</strong><span>{barrier||room.barrier}</span><strong>Strategy</strong><span>{response||room.bestResponse}</span><strong>Review</strong><span>Check task access, pupil usefulness and whether adults used the strategy consistently.</span></div></div>}
 {stage===6&&<div className="erDebrief"><div className="erUnlocked">✓ CASE UNLOCKED</div><h3>Debrief the reasoning, not just the answer.</h3><p><strong>Evidence:</strong> Which clue changed your interpretation most?</p><p><strong>Adult response:</strong> What could have escalated the situation?</p><p><strong>Implementation:</strong> What would staff need to do consistently for the strategy to work?</p><p><strong>Transfer:</strong> Where else in school does this same barrier appear?</p><a className="zsPrimary" href="/zones-cpd">Return to Zones CPD</a></div>}
 {message&&<div className="erFeedback">{message}</div>}<footer><button disabled={stage===0} onClick={()=>setStage(v=>Math.max(0,v-1))}>← Back</button>{stage<6&&<button className="zsPrimary" onClick={next}>Continue →</button>}</footer></article>
 <aside className="erEvidenceBoard"><span className="zsEyebrow">EVIDENCE BOARD</span><strong>{chosenEvidence.length} clues collected</strong>{chosenEvidence.map(i=><div key={i}><small>{evidence[i].kind}</small><p>{evidence[i].text}</p></div>)}<button onClick={()=>reset()}>Reset case</button></aside></section>
 {builderOpen&&<div className="erModal"><div className="erBuilder"><header><div><span className="zsEyebrow">ESCAPE ROOM BUILDER</span><h2>Create a custom case</h2></div><button onClick={()=>setBuilderOpen(false)}>×</button></header><label>Room title<input value={customTitle} onChange={e=>setCustomTitle(e.target.value)}/></label><label>Case scenario<textarea value={customCase} onChange={e=>setCustomCase(e.target.value)} placeholder="Describe the classroom or pastoral situation…"/></label><label>Key evidence clue<textarea value={customClue} onChange={e=>setCustomClue(e.target.value)} placeholder="Add a pupil voice, observation or implementation clue…"/></label><div className="erBuilderPreview"><span>CUSTOM ROOM PREVIEW</span><h3>{customTitle}</h3><p>{customCase||"Your scenario will appear here."}</p><blockquote>{customClue||"Your key clue will appear here."}</blockquote></div><footer><button onClick={()=>setBuilderOpen(false)}>Close</button><button className="zsPrimary" onClick={()=>{localStorage.setItem("staff-development-custom-escape",JSON.stringify({title:customTitle,caseText:customCase,clue:customClue}));setBuilderOpen(false)}}>Save custom room</button></footer></div></div>}
 </main>
}
